#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app


FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["GymWorkDisclosed\GymWorkDisclosed.csproj", "./GymWorkDisclosed/"]
RUN dotnet restore "GymWorkDisclosed\GymWorkDisclosed\GymWorkDisclosed.csproj"
COPY . .
WORKDIR "/src/GymWorkDisclosed"
RUN dotnet build "GymWorkDisclosed.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "GymWorkDisclosed.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "GymWorkDisclosed.dll"]